language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t edwardsingapore/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edwardsingapore/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-563932299517"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY1
  secret_access_key:
    secure: "$AWS_SECRET_KEY1"
