language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t edwardsingapore/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edwardsingapore/docker-react npm run test